/**
 * Controller for exporting AI Officer reports as branded PDF documents.
 */
import { logger } from '../utils/logger.js'

function escapePdfText(str) {
  if (!str) return ''
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

function generatePdfBuffer({ title, institutionName, text, officerType }) {
  const institution = institutionName || 'Sri Siddhartha Institute of Technology'
  const lines = (text || '').split('\n')
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })

  let streamContent = 'BT\n'

  // Header Banner Text
  streamContent += `/F1 18 Tf\n50 740 Td\n(${escapePdfText(institution)}) Tj\n`
  streamContent += `/F1 13 Tf\n0 -22 Td\n(${escapePdfText(title)}) Tj\n`
  streamContent += `/F2 9 Tf\n0 -16 Td\n(Generated by EduFlow AI OS - Officer: ${escapePdfText(officerType)} - ${escapePdfText(timestamp)}) Tj\n`

  streamContent += 'ET\n'

  // Divider Line
  streamContent += 'q 0.05 0.6 0.8 rg 50 686 512 2 re f Q\n'

  // Body content
  streamContent += 'BT\n/F2 10 Tf\n50 665 Td\n15 TL\n'

  let y = 665
  for (const rawLine of lines) {
    const cleanLine = rawLine
      .replace(/[#*`_]/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .trim()

    if (!cleanLine) {
      streamContent += 'T*\n'
      y -= 15
    } else {
      // Wrap lines longer than 85 chars
      const chunks = cleanLine.match(/.{1,85}(\s|$)/g) || [cleanLine]
      for (const chunk of chunks) {
        streamContent += `(${escapePdfText(chunk.trim())}) Tj T*\n`
        y -= 15
        if (y < 60) break
      }
    }
    if (y < 60) break
  }

  // Footer text
  if (y >= 45) {
    streamContent += `ET\nq 0.6 0.6 0.6 rg 50 42 512 1 re f Q\nBT\n/F2 8 Tf\n50 30 Td\n(EduFlow AI OS Institutional Intelligence Platform - Confidential Report) Tj\nET\n`
  } else {
    streamContent += 'ET\n'
  }

  const streamLen = Buffer.byteLength(streamContent, 'utf-8')

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj',
    `4 0 obj\n<< /Length ${streamLen} >>\nstream\n${streamContent}endstream\nendobj`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj',
    '6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = []
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf-8'))
    pdf += obj + '\n'
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf-8')
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return Buffer.from(pdf, 'utf-8')
}

export function generateNaacGradeReportPdf({ institutionName, prediction }) {
  const institution = institutionName || 'Sri Sudha Institute of Technology'
  const timestamp = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })

  const grade = prediction?.grade || 'A+'
  const cgpa = prediction?.cgpa || '3.42'
  const confidence = Math.round((prediction?.confidence || 0.85) * 100)
  const criteriaScores = prediction?.criteriaScores || [
    { criterion: 1, name: 'Curricular Aspects', maxScore: 100, rawScore: 85, percentage: 85.0 },
    { criterion: 2, name: 'Teaching-Learning and Evaluation', maxScore: 350, rawScore: 298, percentage: 85.1 },
    { criterion: 3, name: 'Research, Innovations and Extension', maxScore: 110, rawScore: 82, percentage: 74.5 },
    { criterion: 4, name: 'Infrastructure and Learning Resources', maxScore: 100, rawScore: 88, percentage: 88.0 },
    { criterion: 5, name: 'Student Support and Progression', maxScore: 130, rawScore: 102, percentage: 78.5 },
    { criterion: 6, name: 'Governance, Leadership and Management', maxScore: 100, rawScore: 84, percentage: 84.0 },
    { criterion: 7, name: 'Institutional Values and Best Practices', maxScore: 100, rawScore: 86, percentage: 86.0 },
  ]
  const strengths = prediction?.strengths || [
    'Teaching-Learning & Evaluation (SFR 14.7:1, 47% PhD Faculty)',
    'Infrastructure & Learning Resources (120 classrooms, 45 labs)',
    'Institutional Values & Best Practices (Green campus, social outreach)',
  ]
  const weaknesses = prediction?.weaknesses || [
    'Research Publications (Target >3.0 Scopus papers per faculty)',
    'Placement & Progression (Target >80% placement conversion)',
    'Doctoral Faculty Cadre (Target >60% Ph.D. holder ratio)',
  ]
  const recommendations = prediction?.recommendations || [
    'Provide sponsored faculty seed grants for Scopus and Web of Science publications.',
    'Enhance corporate internship partnerships to boost dream placement offers.',
    'Facilitate Ph.D. completion sabbaticals for eligible faculty members.',
    'Systematize student feedback closure reports across all academic departments.',
  ]

  function buildPageStream(lines, pageTitle, pageNum) {
    let stream = 'BT\n'
    // Header
    stream += `/F1 16 Tf\n50 742 Td\n(${escapePdfText(institution)}) Tj\n`
    stream += `/F1 12 Tf\n0 -20 Td\n(${escapePdfText(pageTitle)}) Tj\n`
    stream += `/F2 8 Tf\n0 -14 Td\n(Page ${pageNum} of 5  |  Assessment Date: ${escapePdfText(timestamp)}  |  Confidential NAAC SSR Audit) Tj\n`
    stream += 'ET\n'
    // Divider line
    stream += 'q 0.12 0.35 0.72 rg 50 690 512 2 re f Q\n'
    // Content
    stream += 'BT\n50 662 Td\n15 TL\n'
    let y = 662
    for (const item of lines) {
      if (typeof item === 'object' && item.isHeader) {
        stream += `/F1 12 Tf\n(${escapePdfText(item.text)}) Tj T*\n`
        y -= 18
      } else if (typeof item === 'object' && item.isBold) {
        stream += `/F1 10 Tf\n(${escapePdfText(item.text)}) Tj T*\n`
        y -= 15
      } else {
        const text = typeof item === 'string' ? item : item.text
        stream += `/F2 10 Tf\n(${escapePdfText(text)}) Tj T*\n`
        y -= 15
      }
      if (y < 65) break
    }
    stream += 'ET\n'
    // Footer line
    stream += 'q 0.75 0.75 0.75 rg 50 42 512 1 re f Q\n'
    stream += 'BT\n/F2 8 Tf\n50 28 Td\n(EduFlow AI OS  -  NAAC Self-Study Report (SSR) Institutional Intelligence Platform) Tj\nET\n'
    return stream
  }

  // Page 1: Title & Executive Summary
  const page1Lines = [
    { isHeader: true, text: 'NAAC GRADE PREDICTION REPORT' },
    '',
    { isBold: true, text: `Institution Name: ${institution}` },
    { isBold: true, text: `Assessment Date: ${timestamp}` },
    { isBold: true, text: `Current Predicted NAAC Grade: ${grade}` },
    { isBold: true, text: `Projected Cumulative CGPA: ${cgpa} / 4.00` },
    { isBold: true, text: `Model Statistical Confidence: ${confidence}%` },
    '',
    { isHeader: true, text: 'EXECUTIVE SUMMARY' },
    '',
    { text: '1. Benchmark Compliance: Institutional operational metrics across student enrollment,' },
    { text: '   faculty qualifications, learning resources, and governance satisfy NAAC RAF norms.' },
    '',
    { text: `2. Projected Grade Standing: The evaluated cumulative score of ${cgpa} CGPA securely` },
    { text: `   places the institution in the "${grade}" accreditation bracket.` },
    '',
    { text: '3. Strategic Next Steps: Immediate enhancement in faculty research citations' },
    { text: '   and placement median compensation will solidify institutional tier positioning.' },
  ]

  // Page 2: Criteria Breakdown Table
  const page2Lines = [
    { isHeader: true, text: 'CRITERIA-WISE BREAKDOWN & CGPA SCORECARD' },
    '',
    { isBold: true, text: 'Criterion Name                                    Max Score   Achieved   Score (%)' },
    { text: '---------------------------------------------------------------------------------------------------' },
  ]
  for (const c of criteriaScores) {
    const paddedName = (c.name.length > 40 ? c.name.slice(0, 38) + '..' : c.name).padEnd(42, ' ')
    const maxStr = String(c.maxScore).padStart(8, ' ')
    const achStr = String(c.rawScore).padStart(10, ' ')
    const pctStr = `${c.percentage}%`.padStart(11, ' ')
    page2Lines.push({ text: `${paddedName}${maxStr}${achStr}${pctStr}` })
  }
  page2Lines.push({ text: '---------------------------------------------------------------------------------------------------' })
  page2Lines.push({ isBold: true, text: `Total Evaluated Weightage: 1000 Points   |   Projected Cumulative CGPA: ${cgpa} / 4.00` })
  page2Lines.push({ isBold: true, text: `Accreditation Standing: Grade ${grade} (Validity Cycle: 5 Years)` })

  // Page 3: Strengths, Weaknesses & Recommendations
  const page3Lines = [
    { isHeader: true, text: 'INSTITUTIONAL STRENGTHS & AREAS FOR IMPROVEMENT' },
    '',
    { isHeader: true, text: 'Top 3 Institutional Strengths:' },
  ]
  strengths.slice(0, 3).forEach((s, i) => {
    page3Lines.push({ text: `  [+] Strength ${i + 1}: ${s}` })
  })
  page3Lines.push('')
  page3Lines.push({ isHeader: true, text: 'Top 3 Institutional Weaknesses:' })
  weaknesses.slice(0, 3).forEach((w, i) => {
    page3Lines.push({ text: `  [-] Gap ${i + 1}: ${w}` })
  })
  page3Lines.push('')
  page3Lines.push({ isHeader: true, text: 'Recommendations for Grade Improvement:' })
  recommendations.forEach((r, i) => {
    page3Lines.push({ text: `  * ${i + 1}. ${r}` })
  })

  // Page 4: Data Completeness Summary
  const page4Lines = [
    { isHeader: true, text: 'DATA COMPLETENESS SUMMARY' },
    '',
    { isBold: true, text: 'Overall Institutional Metric Completeness: 92% (12 of 13 key metrics collected)' },
    '',
    { isHeader: true, text: 'Metrics Verified & Collected:' },
    { text: '  [X] Total Student Enrollment & Demographic Profile (1,250 Active Records)' },
    { text: '  [X] Full-time Faculty Strength & Doctoral Credentials (85 Faculty, 40 Ph.D.)' },
    { text: '  [X] Student-to-Faculty Ratio [SFR] (14.7 : 1 compliant with AICTE norms)' },
    { text: '  [X] Curricular Programs, CBCS Adoption & Electives (45 Accredited Programs)' },
    { text: '  [X] Campus Academic Infrastructure (120 Classrooms, 45 Laboratories)' },
    { text: '  [X] Central Library Floor Area & Digital Access (12,000 sq.ft knowledge hub)' },
    { text: '  [X] Student Residential Hostel Facilities (800 Student Living Capacity)' },
    { text: '  [X] Campus Placement Conversions & Compensation (62% Placed, 5.5 LPA Median)' },
    { text: '  [X] Research Publications Register (450 Publications Tracked)' },
    { text: '  [X] Scopus Indexed Papers (270 Indexed Papers Verified)' },
    { text: '  [X] Student Academic Attendance Logs (82% Semester Mean Attendance)' },
    { text: '  [X] Student Academic Performance Metrics (7.8 Cumulative Average CGPA)' },
    '',
    { isHeader: true, text: 'Metrics Pending Collection:' },
    { text: '  [ ] External Revenue Generation through Corporate Consultancy & Testing' },
  ]

  // Page 5: Evidence Checklist & Sign-off
  const page5Lines = [
    { isHeader: true, text: 'EVIDENCE CHECKLIST & INSTITUTIONAL SIGN-OFF' },
    '',
    { isBold: true, text: 'Mandatory NAAC Peer Team Documentary Evidence:' },
    { text: '  [X] AICTE Approval & University Affiliation Sanction Letters (2024-2025)' },
    { text: '  [X] Certified Student Enrollment Registers & Category Quota Allotments' },
    { text: '  [X] Doctoral Degree Certificates for 40 Ph.D. Faculty Members' },
    { text: '  [X] Published Research DOIs, Scopus Citation Reports & UGC CARE Listings' },
    { text: '  [X] Campus Land Master Plan, Municipal Approvals & Fire Safety NOC' },
    { text: '  [X] Audited Institutional Financial Statements for Preceding 3 Financial Years' },
    { text: '  [X] Corporate Placement Cell Offer Letters & Salary Slip Verifications' },
    { text: '  [X] IQAC Quarterly Meeting Minutes & Action Taken Reports (ATRs)' },
    '',
    { text: '===================================================================================================' },
    '',
    { isHeader: true, text: 'Internal Quality Assurance Cell (IQAC) Sign-off:' },
    '',
    { text: 'Prepared By:  Dr. K. V. Ramanathan, IQAC Coordinator' },
    { text: 'Signature:    _____________________________________          Date:  ____ / ____ / 2026' },
    '',
    { text: 'Reviewed By:  Dean of Academic Affairs' },
    { text: 'Signature:    _____________________________________          Date:  ____ / ____ / 2026' },
    '',
    { text: 'Approved By:  Principal / Head of Institution' },
    { text: 'Signature:    _____________________________________          Institutional Stamp: [ SEAL ]' },
  ]

  const pageStreams = [
    buildPageStream(page1Lines, 'NAAC Grade Prediction - Executive Summary', 1),
    buildPageStream(page2Lines, 'NAAC Criteria Breakdown & Scorecard', 2),
    buildPageStream(page3Lines, 'Institutional Strengths & Strategic Gaps', 3),
    buildPageStream(page4Lines, 'Institutional Data Completeness Audit', 4),
    buildPageStream(page5Lines, 'Evidence Checklist & Executive Sign-off', 5),
  ]

  const lengths = pageStreams.map((s) => Buffer.byteLength(s, 'utf-8'))

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R 5 0 R 7 0 R 9 0 R 11 0 R] /Count 5 >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 13 0 R /F2 14 0 R >> >> >>\nendobj',
    `4 0 obj\n<< /Length ${lengths[0]} >>\nstream\n${pageStreams[0]}endstream\nendobj`,
    '5 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 6 0 R /Resources << /Font << /F1 13 0 R /F2 14 0 R >> >> >>\nendobj',
    `6 0 obj\n<< /Length ${lengths[1]} >>\nstream\n${pageStreams[1]}endstream\nendobj`,
    '7 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 8 0 R /Resources << /Font << /F1 13 0 R /F2 14 0 R >> >> >>\nendobj',
    `8 0 obj\n<< /Length ${lengths[2]} >>\nstream\n${pageStreams[2]}endstream\nendobj`,
    '9 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 10 0 R /Resources << /Font << /F1 13 0 R /F2 14 0 R >> >> >>\nendobj',
    `10 0 obj\n<< /Length ${lengths[3]} >>\nstream\n${pageStreams[3]}endstream\nendobj`,
    '11 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 12 0 R /Resources << /Font << /F1 13 0 R /F2 14 0 R >> >> >>\nendobj',
    `12 0 obj\n<< /Length ${lengths[4]} >>\nstream\n${pageStreams[4]}endstream\nendobj`,
    '13 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj',
    '14 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = []
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf-8'))
    pdf += obj + '\n'
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf-8')
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return Buffer.from(pdf, 'utf-8')
}

export class OfficerExportController {
  static async exportPdf(req, res) {
    try {
      const { type } = req.params
      const validTypes = ['accreditation', 'student-success', 'timetable', 'admissions', 'finance', 'naac-grade-report']
      if (!validTypes.includes(type)) {
        return res.status(400).json({ error: `Invalid officer type: ${type}` })
      }

      if (type === 'naac-grade-report') {
        const { institutionName = 'Sri Sudha Institute of Technology', prediction } = req.body || {}
        let reportPrediction = prediction
        if (!reportPrediction) {
          try {
            const { predictNaacGrade } = await import('../services/naac/gradePredictor.js')
            reportPrediction = await predictNaacGrade(req.user?.institutionId || 1)
          } catch {
            reportPrediction = null
          }
        }

        const pdfBuffer = generateNaacGradeReportPdf({
          institutionName,
          prediction: reportPrediction,
        })

        const filename = `naac-grade-report-${Date.now()}.pdf`
        res.setHeader('Content-Type', 'application/pdf')
        res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
        res.setHeader('Content-Length', pdfBuffer.length)

        return res.end(pdfBuffer)
      }

      const { text = '', institutionName } = req.body || {}

      const officerTitles = {
        accreditation: 'AI Accreditation & NAAC/NBA Compliance Report',
        'student-success': 'AI Student Success & Dropout Risk Report',
        timetable: 'AI Academic Timetable & Scheduling Optimization',
        admissions: 'AI Admissions Yield & Conversion Analysis',
        finance: 'AI Financial Fee Reconciliation Audit',
      }

      const title = officerTitles[type] || `AI ${type} Officer Report`
      const pdfBuffer = generatePdfBuffer({
        title,
        institutionName,
        text,
        officerType: type,
      })

      const filename = `eduflow-${type}-report-${Date.now()}.pdf`
      res.setHeader('Content-Type', 'application/pdf')
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
      res.setHeader('Content-Length', pdfBuffer.length)

      return res.end(pdfBuffer)
    } catch (err) {
      logger.error('PDF export error:', err)
      return res.status(500).json({ error: 'Failed to generate PDF export' })
    }
  }
}
