name: eduflow_app
description: "EduFlow AI OS Mobile Client."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  dio: ^5.11.0
  shared_preferences: ^2.5.5
  go_router: ^17.3.0
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0A2540"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"

flutter_native_splash:
  color: "#0A2540"
  image: "assets/icon/app_icon_foreground.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
